In [ ]:
import cv2
import numpy as np
from scipy.stats import skew

In [ ]:

def resize_img(file_path):
    img = cv2.imread(file_path)
    img = cv2.resize(img, (300, 100))
    image_color = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    
    grid_rows, grid_colum = 10, 10
    cell_height = image_color.shape[0] // grid_rows  # = 10
    cell_space  = image_color.shape[1] // grid_colum  # = 30

    features = []
    for i in range(grid_rows):
        for j in range(grid_colum):
            y_start, y_end = i * cell_height, (i + 1) * cell_height
            x_start, x_end = j * cell_space,  (j + 1) * cell_space
            cell = image_color[y_start:y_end, x_start:x_end, :]  # (10, 30, 3)

            for channel in range(3):  # R, G, B
                values = cell[:, :, channel].flatten()
                mean_val = np.mean(values)
                std_val  = np.std(values)
                skew_val = skew(values)

                features.extend([mean_val, std_val, skew_val])

    return np.array(features)


In [ ]:
feature_vector = resize_img("/workspaces/dbm25/data/Part1/Part1/brain_menin/brain_menin_0001.jpg")
#print("Dimensione del vettore:", feature_vector.shape)  # Output: (900,)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 1 1 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 1 4]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 1 1 4]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 1 0 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 1 0 2]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 2 0 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 2 0 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 3 4 3 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 3 3 5 3]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 1 1 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 1 4]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 1 1 4]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 1 0 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 1 0 2]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 

/tmp/ipykernel_2444/1313512677.py:22: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew_val = skew(values)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (900,) + inhomogeneous part.